### ISSUE TITLE
Add MIDI Input allowing incoming MIDI Program Changes to trigger row sends.

### ISSUE THREAD

**Issue by rockumk** [masc4ii/SysexLive#2]
It would be great to be able to send a MIDI program change to the App and have it send a row in response.

![NewFeature](https://user-images.githubusercontent.com/11165312/73216954-a4eb5f80-411c-11ea-9ba8-a2ca3c6262b4.png)

**Comment by masc4ii** [comment]
Thanks for this idea. I will think about how I could do this! :)

**Comment by rockumk** [comment]
I think I got it working. It was my first attempt to do something in C++ or QT so there are likely issues with my code, but I'll try to branch or fork the project so you can see what needs cleaning up.

**Comment by masc4ii** [comment]
Really? Great! Yes, fork it, and if you like: create a pull request!

**Comment by rockumk** [comment]
I was having more trouble figuring out github than QT or C++ and didn't know how to correctly fork or branch the project. 

I found a video on creating a new repository and just followed that way of uploading the files. Hope that did not break any rules. No disrespect meant.

[https://github.com/rockumk/SysLPX](url)

Adds:

- Row selection via incoming MIDI Program Changes.
- Number of Synths changed from 2 to 4.
- Loads patchlist "default.syxml" by default.
- New last row which loads row with a double-click.

Issues

- Not sure I provided for systems with no MIDI input.
- Most if not all new lines and/or sections marked with "rockumk" so that my poor programming could be quickly checked.
- Couldn't figure out how to send row with a single rather than double click or how to make the cell non-editable.
- Had to use a different version of Qmidi which inlcuded the ablitity to check if the MIDI input port was open and close it.
- I had to add a line to Qmidi's qmidiin.cpp to deal with Program changes.
- Probably others I can't think of.

Hope you don't mind checking it over. Use or discard any changes you wish.

**Comment by rockumk** [comment]
I deleted all of the files at the SysLPX repository except those with changes.

**Comment by masc4ii** [comment]
Thanks! Lots of changes :) 
I hope to find some time to check it soon!

**Comment by masc4ii** [comment]
I just reviewed the code... looks not bad so far. But I need my instruments to try it out.

What's the last column in the table? "a"? You wanted to have it for just clicking on it and sending patches? Have you tried calling the function on_tableWidget_clicked(.. instead of on_tableWidget_Clicked(.. ?

Just have my laptop here. I hope being able to check that out! ;)

**Comment by masc4ii** [comment]
Did you test the latest changes from 12 March?

**Comment by rockumk** [comment]
No, I look forward to trying it later today. Thanks.

**Comment by rockumk** [comment]
Hey, sorry I didn't get back to you. My computer went down and because of Covid I was unable to get a new power supply for weeks. When I got back going, I had forgotten to get back to this. My apologies. I appreciate you adding the feature and hope others will find it useful as well.

**Comment by masc4ii** [comment]
Oh... you're still there... sry! Hope you're satisfied with the realization. Thank you so much for the idea. I find it very useful and use it a lot myself.

**Comment by rockumk** [comment]
Awesome. I'm glad to hear that.
